spring:
  servlet:
    multipart:
      max-file-size: 50MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.202:3306/tmp_common_db?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    platform: mysql

logging:
  file:
    path: logs
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss
  level:
    root: warn
    sql: error
    com.yoyohr: info
    org.springframework.boot.autoconfigure.logging: error